<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>Eshop</h1>
    </header>
    <main>
        <table>
            <thead>
                <th>ID</th>
                <th>Nom du produit</th>
                <th>Catégorie</th>
                <th>Prix</th>
            </thead>
            <tbody>
                <?php foreach ($products as $product): ?>
                    <tr>
                        <td><?=$product['productId']?></td>
                        <td><?=$product['name']?></td>
                        <td><?=$product['category']?></td>
                        <td><?=number_format($product['price']/100, 2, ',');?> €</td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </main>
</body>
</html>