<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Painter SVG</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <h1>Painter SVG</h1>
    </header>
    <main>
        <svg id="painter" width="1200" height="400">
            <?php // echo genRectangle(100, 50, 200, 150, 'crimson', 1)?>
            <!-- <rect x="150" y="100" width="75" height="75" fill="forestgreen" opacity="1" />
            <ellipse cx="300" cy="200" rx="50" ry="80" fill="orange" opacity="0.5" />
            <circle cx="100" cy="150" r="30" fill="red" opacity="1" />
            <polygon points="10 50 150 75 260 128" fill="blue" opacity="0.3" />
            <polygon points="100 150 120 40 360 180 200 190 250 300" fill="violet" opacity="0.8" /> -->
            <?=$svg?>
        </svg>
    </main>
</body>
</html>