<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon super site</title>
</head>
<body>
    <header>
        <nav>
            <a href="index.php">Accueil</a>
            <?php if (!isConnected()): ?>
                <a href="signup.php">Créer un compte</a>
                <a href="login.php">Connexion</a>
            <?php else: ?>
                <a href="profile.php">Mon profil</a>
                <a href="logout.php">Déconnexion</a>
            <?php endif; ?>
        </nav>
    </header>
    <main>
        <!-- inclusion du fichier de template -->
        <?php include $template . '.phtml'; ?>
    </main>
</body>
</html>