<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Création compte client</title>
</head>
<body>

<h1>Création de compte client</h1>

  <form action="index.php" method="post">

    <label for="lastname">Nom :</label>
    <input type="text" id="lastname" name="lastname"><br>

    <label for="firstname">Prénom :</label>
    <input type="text" id="firstname" name="firstname"><br>

    <label for="birthdate">Date de naissance :</label>
    <input type="date" id="birthdate" name="birthdate"><br>

    <label for="email">Email :</label>
    <input type="email" id="email" name="email"><br>

    <label for="password">Mot de passe :</label>
    <input type="password" id="password" name="password"><br>

    <label for="newsletter">S'abonner à la newsletter :</label>
    <input type="checkbox" id="newsletter" name="newsletter" value="1"><br>

    <input type="submit" value="Créer compte">
  </form>

</body>
</html>