<h1>Connexion</h1>

<!-- MEssage d'erreur le cas échéant -->
<?php if($error != null) : ?>
    <p><?=$error;?></p>
<?php endif; ?>

<form action="login.php" method="POST">
    <div>
        <label for="email">Email</label>
        <input type="email" id="email" name="email" value="">
    </div>
    <div>
        <label for="password">Mot de passe</label>
        <input type="password" id="password" name="password">
    </div>
    <input type="submit" value="Connexion">
</form>