<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <header>
        <h1>Tirage du loto</h1>
    </header>
    <main>
        <!-- la fonction implode() concatène tous les éléments d'un tableau en les séparant par son preier paramètre -->
        <!-- implode() : tableau => chaîne de caractères -->
        <!-- explode() : chaîne de cractères => tableau -->

        <p>Le tirage du jour est : <?php echo implode(' ', $tirage); ?></p>
    </main>
</body>

</html>