<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>Eshop</h1>
        <p>Panier (<?=$nProducts;?>)</p>
    </header>
    <main>
        <table>
            <thead>
                <th>ID</th>
                <th>Nom du produit</th>
                <th>Catégorie</th>
                <th>Prix</th>
                <th></th>
            </thead>
            <tbody>
                <?php foreach ($products as $product): ?>
                    <tr>
                        <td><?=$product['productId']?></td>
                        <td><?=$product['name']?></td>
                        <td><?=$product['category']?></td>
                        <td><?=number_format($product['price']/100, 2, ',');?> €</td>
                        <td>
                            <form style="display:flex;" action="addToCart.php" method="POST">
                                <input type="hidden" name="id-product" value="<?=$product['productId']?>">
                                <div>
                                    <label for="quantity">Quantité</label>
                                    <select id="quantity" name="quantity">
                                        <?php for ($i = 1; $i <= 10; $i++): ?>
                                            <option value="<?=$i;?>"><?=$i;?></option>
                                        <?php endfor; ?>
                                    </select>
                                </div>
                                <input type="submit" value="Ajouter au panier">
                            </form>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </main>
</body>
</html>