<!-- Le code HTML du corps de la page Article --> 
<article class="article-details">
    <h2><?=$article->getTitle();?></h2>
    <p>Créé le <?=$article->getFormattedCreatedAt();?></p>
    <div class="badge article-category mb-3"><?=$article->getCategoryName();?></div>
    <?php if ($article->getImage()): ?>
        <img src="<?=asset('images/' . $article->getImage())?>" alt="" class="card-img-top mb-2">
    <?php endif; ?>
    <p class="card-text"><?=$article->getContent();?></p>
</article>

<section>
    <h2>Commentaires</h2>
    <form action="<?=constructUrl('/article', ['id' => $idArticle])?>" method="POST">
        <fieldset>
            <legend>Ajouter un commentaire</legend>
            <div>
                <label for="nickname">Pseudo</label>
                <input type="text" id="nickname" name="nickname">
                <?php if (isset($errors['nickname'])): ?>
                    <p class="error"><?=$errors['nickname']?></p>
                <?php endif; ?>
            </div>
            <div>
                <label for="content">Commentaire</label>
                <textarea id="content" name="content"></textarea>
                <?php if (isset($errors['content'])): ?>
                    <p class="error"><?=$errors['content']?></p>
                <?php endif; ?>
            </div>
            <input type="submit" value="Valider">
        </fieldset>
    </form>

    <?php if(empty($comments)): ?>
        <p>Soyez le premier à ajouter un commentaire !</p>
    <?php else: ?>
        <?php foreach ($comments as $comment): ?>
            <div>
                <h3>Ajouté par <?=$comment->getNickname();?> le <?=$comment->getFormattedCreatedAt();?></h3>
                <p><?=$comment->getContent();?></p>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

</section>